
import Navbar from '@/Components/Navbar'
import './globals.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='mx-6 bg-black text-white'>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
